### ISSUE TITLE
Errno::EACCES when $HOME is not set or not accessible

### ISSUE THREAD

**Issue by alexeckermann** [heroku/netrc#20]
I've just encountered a rather curly issue:

```
Errno::EACCES: Permission denied @ rb_file_s_stat - /root/.netrc
…/app/ruby/2.1.0/gems/netrc-0.7.7/lib/ netrc.rb:  19:in `stat'
…/app/ruby/2.1.0/gems/netrc-0.7.7/lib/ netrc.rb:  19:in `check_permissions'
…/app/ruby/2.1.0/gems/netrc-0.7.7/lib/ netrc.rb:  28:in `read'
```

This was a production environment running on Ububtu 14.04 on AWS OpsWorks, Ruby 2.1.0, Rails 4.1.4, netrc 0.7.7.

From what I gathered from the error was that the `HOME` env was set incorrectly and the path resolved was not accessible to the user operating the rails environment. My fix was to set the `HOME` env to an accessible path for the Rails environment. At the moment I am not sure how the `HOME` was incorrect to begin with — it is a clean Chef setup with little modification and should have been available.

Would there be any improvements where the `check_permissions` method will rescue from an exception like this or is it meant to bubble up? The parent gem, stripe, was allowing the exception to bubble regardless.

**Comment by agrass** [comment]
@Aerlinger I have the same problem on Opsworks.  Please share if you got some workaround. Thanks

**Comment by dickeyxxx** [comment]
you will need read/write access to `$HOME/.netrc`
