### ISSUE TITLE
ArgumentError: couldn't find HOME environment -- expanding `~'

### ISSUE THREAD

**Issue by wulffeld** [heroku/netrc#31]
After updating Gemfile and using latest netrc a standard resque:work fails to start via monit:

monit line:

```
 bundle exec rake environment resque:work
```

```
ArgumentError: couldn't find HOME environment -- expanding `~'
.../shared/bundle/ruby/2.1.0/gems/netrc-0.10.0/lib/netrc.rb:15:in `home'
.../shared/bundle/ruby/2.1.0/gems/netrc-0.10.0/lib/netrc.rb:15:in `home_path'
.../shared/bundle/ruby/2.1.0/gems/netrc-0.10.0/lib/netrc.rb:11:in `default_path'
.../shared/bundle/ruby/2.1.0/gems/netrc-0.10.0/lib/netrc.rb:50:in `read'
.../shared/bundle/ruby/2.1.0/gems/rest-client-1.7.2/lib/restclient/request.rb:284:in `parse_url_with_auth'
.../shared/bundle/ruby/2.1.0/gems/rest-client-1.7.2/lib/restclient/request.rb:175:in `execute'
.../shared/bundle/ruby/2.1.0/gems/rest-client-1.7.2/lib/restclient/request.rb:41:in `execute'
.../shared/bundle/ruby/2.1.0/gems/rest-client-1.7.2/lib/restclient.rb:85:in `head'
.../shared/bundle/ruby/2.1.0/gems/tire-0.6.2/lib/tire/http/client.rb:43:in `head'
.../shared/bundle/ruby/2.1.0/gems/tire-0.6.2/lib/tire/index.rb:18:in `exists?'
.../shared/bundle/ruby/2.1.0/gems/tire-0.6.2/lib/tire/model/indexing.rb:107:in `create_elasticsearch_index'
.../shared/bundle/ruby/2.1.0/gems/tire-0.6.2/lib/tire/model/indexing.rb:61:in `mapping'
.../shared/bundle/ruby/2.1.0/gems/tire-0.6.2/lib/tire/model/search.rb:300:in `mapping'
...
```

Not quite sure if it's a bug in netrc.

**Comment by hiattp** [comment]
I'm seeing this as well on sidekiq workers using `rest-client` in a Rails app on AWS elastic beanstalk. Oddly it only fails ~50% of the time. Thoughts?

**Comment by hiattp** [comment]
`Dir.pwd` is throwing `Errno::ENOENT: No such file or directory - getcwd`, so it rescues the `ArgumentError` only to throw a different one

**Comment by dickeyxxx** [comment]
@hiattp if I'm understanding right this means you don't have a home directory and pwd is empty? You couldn't really expect it to find a netrc file in that case I don't think

**Comment by dickeyxxx** [comment]
er not empty but pwd doesn't exist?

**Comment by hiattp** [comment]
@dickeyxxx Hey sorry, didn't swing back around on this when I found the fix. This happened when a sidekiq process failed to shut down across a deployment and then it tried to use netrc; that seemed to cause all kinds of weirdness including this error.

**Comment by drewish** [comment]
We're using rest-client and I saw this consistently when looking into the exceptions during requests. It seems to just be thrown and caught as flow control rather than any kind of an error.
