### ISSUE TITLE
Missing v0.11.0 release tag and archive.

### ISSUE THREAD

**Issue by bartoszkosiorek-tomtom** [heroku/netrc#54]
The latest release tag is v0.10.0:
https://github.com/heroku/netrc/releases/tag/v0.10.0

but the release 0.11.0 was already made and it is used by gem:
https://rubygems.org/gems/netrc/versions/0.11.0

It will be great to add missing tag, and archive:
https://github.com/heroku/netrc/tags

**Comment by beanieboi** [comment]
sorry for that, I created the tag and added it as release on GitHub

**Comment by bartoszkosiorek-tomtom** [comment]
Thanks for fast fixing!
